---   #Every Ansible Playbook starts with 3 "-"
- name: SuiteCRM           #Name of the playbook
  hosts: all           #Affects all hosts
  gather_facts: true   #Get variable names and facts
  become: true         #Become root when running the commands 
  
  tasks: 
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest
      
  - name: install git
    yum:
      name: git
      state: latest
      
  - name: install epel
    yum:
      name: epel-release
      state: latest
    
  - name: create suitecrm directory 
    file:
      path: /tmp/suitecrm
      state: directory
      
  - name: download suitecrm installer
    git:
      dest: /tmp/suitecrm
        repo: https://github.com/salesagility/SuiteCRM
