---   #Every Ansible Playbook starts with 3 "-"
- name: SuiteCRM           #Name of the playbook
  hosts: localhost          #Affects LOCAL machine
  gather_facts: true   #Get variable names and facts
  become: true         #Become root when running the commands 
  
  tasks: 
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest
      
  - name: install git
    yum:
      name: git
      state: latest
      
  - name: install epel
    yum:
      name: epel-release
      state: latest
      
  - name: create suitecrm directory 
    file:
      path: /tmp/suitecrm
      state: directory
      
  - name: download suitecrm installer
    git:
      repo: 'https://github.com/salesagility/SuiteCRM.git'
      dest: /tmp/suitecrm
      
  - name: download latest php 
    get_url:
      url: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm   
      dest: /tmp
      
  - name: install php rpm 
    yum:
      name: /tmp/webtatic-release.rpm  
      state: present
      
  - name: install all php packages required
    yum:
      name: 
        - php70w
        - php70w-mysql
        - php70w-xml
        - php70w-json
        - php70w-gd
        - php70w-mbstring
        - php70w-zip
        - php70w-imap
        - php70w-pcre
        - php70w-zlib
        - php70w-curl
      state: latest
      
  - name: restart apache
      name: httpd
      enabled: yes
      state: restarted
      
  - name: give apache permission to /var/www
    file:
      dest: /var/www
      owner: apache
      group: apache
      
      
