---   #Every Ansible Playbook starts with 3 "-"
- name: Nextcloud           #Name of the playbook
  hosts: localhost          #Affects LOCAL machine
  gather_facts: true   #Get variable names and facts
  become: true         #Become root when running the commands 

#Install apache
  tasks: 
   - name: install the latest version of Apache
     yum:
       name: httpd
       state: latest

#Install IUS Community Repo 

#Enable IUS Community Repo

#Download IUS GPG-KEY

#Install PHP and required modules

#Setup Firewall Rules
  - name: Open port 80
     firewalld:
       port: 80/tcp
       permanent: yes
       state: enabled

#Download Nextcloud Installer

#Unzip the installer to /var/www/html

#Change ownership of nextcloud to apache

#Add custom apache VHost file

#Restart Apache

#Setup Database
