---   #Every Ansible Playbook starts with 3 "-"
- name: SuiteCRM           #Name of the playbook
  hosts: localhost          #Affects LOCAL machine
  gather_facts: true   #Get variable names and facts
  become: true         #Become root when running the commands 
  
  tasks: 
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest
      
  - name: install git
    yum:
      name: git
      state: latest
      
  - name: install epel
    yum:
      name: epel-release
      state: latest
      
  - name: create suitecrm directory 
    file:
      path: /tmp/suitecrm
      state: directory
      
  - name: download suitecrm installer
    get_url: https://suitecrm.com/files/162/SuiteCRM-7.11/513/SuiteCRM-7.11.15.zip
      
  - name: move suitecrm folder to /var/www/html
    command: mv /tmp/suitecrm /var/www/html
      
       #Modify this task to download php from IUS Community Repo which is a more secure version of PHP
  - name: download latest php 
    command: curl 'https://setup.ius.io/' -o setup-ius.sh  
 
  #- name: run IUS install script 
  #  sh: setup-ius.sh
 
  - name: install all php packages required
    yum:
      name: 
        - php74
        - php74-mysql
        - php74-xml
        - php74-json
        - php74-gd
        - php74-mbstring
        - php74-zip
        - php74-imap
        - php74-pcre
        - php74-zlib
        - php74-curl
      state: latest
      
  - name: give apache permission to /var/www/html/suitecrm
    file:
      dest: /var/www/html/suitecrm
      state: directory 
      owner: apache
      group: apache
      recurse: yes
      
  - name: Open port 80
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
      
  - name: Reload firewall
    command: firewall-cmd --reload
    
  - name: restart apache
    service: 
      name: httpd
      enabled: yes
      state: reloaded
      
  - name: install composer package
    yum:
      name: composer
      state: latest
    
  - name: install composer in suitecrm
    command: composer install    
    args: 
      chdir: /var/www/html/suitecrm 
