---   #Every Ansible Playbook starts with 3 "-"
- name: SuiteCRM           #Name of the playbook
  hosts: localhost          #Affects LOCAL machine
  gather_facts: true   #Get variable names and facts
  become: true         #Become root when running the commands 
  
  tasks: 
  - name: install the latest version of Apache
    yum:
      name: httpd
      state: latest
      
  - name: install git
    yum:
      name: git
      state: latest
      
  - name: install epel
    yum:
      name: epel-release
      state: latest      

  - name: install unzip
    yum:
      name: unzip
      state: latest  

  - name: create suitecrm install directory 
    file:
      path: /tmp/suitecrm
      state: directory

  - name: unzip suitecrm  
    unarchive: 
      src: https://suitecrm.com/files/162/SuiteCRM-7.11/513/SuiteCRM-7.11.15.zip
      dest: /tmp/suitecrm
      remote_src: yes

  - name: move suitecrm folder to /var/www/html
    command: mv /tmp/suitecrm/SuiteCRM-7.11.15 /var/www/html/suitecrm
    
  - name: download IUS community Repo for PHP
    yum:
      name: https://repo.ius.io/ius-release-el7.rpm
      state: latest
     
  - name: download IUS community Repo for PHP
    command: rpm -Uvh ius-release-el7.rpm
    
  - name: install all php packages required
    yum:
      name: 
        - php
        - php-mysql
        - php-xml
        - php-json
        - php-gd
        - php-mbstring
        - php-zip
        - php-imap
        - php-pcre
        - php-zlib
        - php-curl
      state: latest
      
  - name: give apache permission to /var/www/html/suitecrm
    file:
      dest: /var/www/html/suitecrm
      state: directory 
      owner: apache
      group: apache
      recurse: yes
      
  - name: Open port 80
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
      
  - name: Reload firewall
    command: firewall-cmd --reload
    
  - name: restart apache
    service: 
      name: httpd
      enabled: yes
      state: reloaded
      
  - name: install composer package
    yum:
      name: composer
      state: latest
    
  - name: install composer in suitecrm
    command: composer install    
    args: 
      chdir: /var/www/html/suitecrm 
