#The playbook will do the following
#1. Download the latest version of java CHECK 
#2. Create directory named software CHECK
#3. Download the jira bin file from atlassian website CHECK
#4. Run command chmod 700 bin-file to give it permissions CHECK
#5. Run through the jira executable: ./bin CHECK
#6. Create firewall rules for jira like opening port 8080
#7. Enable the jira service for future use

---   #Every Ansible Playbook starts with 3 "-"
- name: Jira           #Name of the playbook
  hosts: all           #Affects all hosts
  gather_facts: true   #Get variable names and facts
  become: true         #Become root when running the commands 
  
  tasks: 
    - name: install java
      yum:
        name:
          - java
      state: latest
      
    - name: Make software directory #Creates directory ~/software
      file:      
        path: ~/software
        state: directory   
      
    - name: download jira from atlassian website   #Name of the task
      get_url:      #This functions means we need to download something from a URL 
        url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-core-8.7.1-x64.bin   #This performs the download
        dest: ~/software   #This is where our file is being downloaded too
        
    - name: chmod 700 jira-install-bin
      file: 
        path: ~/software/atlassian-jira-core-8.7.1-x64.bin
        owner: root
        group: root
        mode: 700
        
    - name: Move response file to installation directory 
      command: mv ~/Ansible/jira/response.varfile ~/software/   

    - name: Run through installer using silent install #Silent install means it ignores all the questions like do you want to install jira y/n
      script: ~/software/atlassian-jira-core-8.7.1-x64.bin -q -varfile ~/software/response.varfile 
      
    - name: Open port 8080
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
      
    - name: Reload firewall
      command: firewall-cmd --reload
      
    - name: enable jira service
      service:
        name: 'jira'
        enabled: yes
        
    - name: Make jira systemd service
      command: cp ~/Ansible/jira/jira.service /lib/systemd/system/jira.service
      
    - name: chmod 664 jira.service 
      file: 
        path: /lib/systemd/system/jira.service
        owner: root
        group: root
        mode: 664
     
    - name: enable jira service for systemd
      systemctl:
        name: 'jira'
        enabled: yes
              
    #- name: extract jira packages
     # unarchive: 
      #  src: ~/software/atlassian-jira-software-8.7.1-x64.bin
       # remote_src: yes
        #dest: ~/software #LAST THING I EDITED
    
   # - name: start jira services    #This task will ensure that even though we log out from the server, the service continously runs in the background
    #  shell: /opt/atlassian/jira/bin/startup.sh #This is the shell command being ran 
    
